<#
.SYNOPSIS
    Creates a Nexus FOMOD installer package for PackRat.
.DESCRIPTION
    Syncs Mono and IL2CPP assemblies into FOMOD structure, generates Info.xml and ModuleConfig.xml,
    and creates a versioned zip for Nexus Mods.
.PARAMETER ProjectRoot
    Path to the project root directory.
.PARAMETER Version
    Version string (e.g. 1.0.0). If not provided, extracted from MainMod.cs.
#>
param(
    [Parameter(Mandatory = $false)]
    [string]$ProjectRoot = (Resolve-Path "$PSScriptRoot\..").Path,

    [Parameter(Mandatory = $false)]
    [string]$Version = ""
)

$ErrorActionPreference = "Stop"

$ModName = "PackRat"
$AssetDir = Join-Path $ProjectRoot "assets"
$BinRoot = Join-Path $ProjectRoot "bin"

# Get version from MainMod.cs if not provided
if ([string]::IsNullOrWhiteSpace($Version)) {
    $mainModPath = Join-Path $ProjectRoot "MainMod.cs"
    $mainModContent = Get-Content -LiteralPath $mainModPath -Raw
    if ($mainModContent -match 'Version\s*=\s*"([^"]+)"') {
        $Version = $Matches[1]
    }
    else {
        throw "Could not extract Version from MainMod.cs"
    }
}

# Resolve assembly paths
$il2cppConfigs = @("Debug IL2CPP", "Release IL2CPP")
$monoConfigs = @("Debug Mono", "Release Mono")

$il2cppAssembly = $null
$monoAssembly = $null

foreach ($config in $il2cppConfigs) {
    $path = Join-Path $BinRoot "$config\net6\$ModName-IL2CPP.dll"
    if (Test-Path -LiteralPath $path) {
        $il2cppAssembly = (Resolve-Path -LiteralPath $path).Path
        break
    }
}
foreach ($config in $monoConfigs) {
    $path = Join-Path $BinRoot "$config\netstandard2.1\$ModName-Mono.dll"
    if (Test-Path -LiteralPath $path) {
        $monoAssembly = (Resolve-Path -LiteralPath $path).Path
        break
    }
}

if (-not $il2cppAssembly) {
    throw "IL2CPP assembly not found. Build with 'dotnet build -c ""Debug IL2CPP""'."
}
if (-not $monoAssembly) {
    throw "Mono assembly not found. Build with 'dotnet build -c ""Debug Mono""'."
}

function Ensure-Directory {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

$fomodRootPath = Join-Path $BinRoot "FOMod\Mods\PackRat"
$fomodMetaPath = Join-Path $fomodRootPath "fomod"
$infoPath = Join-Path $fomodMetaPath "Info.xml"
$moduleConfigPath = Join-Path $fomodMetaPath "ModuleConfig.xml"

Ensure-Directory -Path $fomodMetaPath

# Runtime data folders
$il2cppModsDir = Join-Path $fomodRootPath "data\Runtime\IL2CPP\Mods"
$monoModsDir = Join-Path $fomodRootPath "data\Runtime\Mono\Mods"
Ensure-Directory -Path $il2cppModsDir
Ensure-Directory -Path $monoModsDir

# Clear old DLLs
Get-ChildItem -Path $il2cppModsDir -File -Filter "*.dll" -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
Get-ChildItem -Path $monoModsDir -File -Filter "*.dll" -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue

# Copy assemblies
Copy-Item -LiteralPath $il2cppAssembly -Destination (Join-Path $il2cppModsDir (Split-Path -Path $il2cppAssembly -Leaf)) -Force
Copy-Item -LiteralPath $monoAssembly -Destination (Join-Path $monoModsDir (Split-Path -Path $monoAssembly -Leaf)) -Force
Write-Host "Synced IL2CPP and Mono assemblies to FOMOD structure"

# Info.xml
$infoXml = @"
<fomod>
  <Name>PackRat</Name>
  <Author>SirTidez</Author>
  <Version>$Version</Version>
  <Description>Portable backpack storage for Schedule One.</Description>
</fomod>
"@
Set-Content -LiteralPath $infoPath -Value $infoXml -Encoding UTF8
Write-Host "Updated FOMOD Info.xml"

# ModuleConfig.xml
$pluginXmlLines = @"
                        <plugin name="PackRat - IL2CPP">
                            <description>Install the IL2CPP build for current Schedule I versions.</description>
                            <files>
                                <folder source="data\Runtime\IL2CPP\Mods" destination="Mods" alwaysInstall="false" installIfUsable="true" priority="0" />
                            </files>
                            <typeDescriptor>
                                <type name="Required" />
                            </typeDescriptor>
                        </plugin>
                        <plugin name="PackRat - Mono">
                            <description>Install the Mono build for legacy/alternate Schedule I Mono setups.</description>
                            <files>
                                <folder source="data\Runtime\Mono\Mods" destination="Mods" alwaysInstall="false" installIfUsable="true" priority="0" />
                            </files>
                            <typeDescriptor>
                                <type name="Required" />
                            </typeDescriptor>
                        </plugin>
"@

$moduleConfigXml = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by package-fomod.ps1 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://qconsulting.ca/fo3/ModConfig5.0.xsd">
`t<moduleName>PackRat</moduleName>
`t<installSteps order="Explicit">
`t`t<installStep name="Runtime - Main/Beta: IL2CPP, Alternate/Alternate Beta: Mono">
`t`t`t<optionalFileGroups>
`t`t`t`t<group name="Runtime" type="SelectExactlyOne">
`t`t`t`t`t<plugins>
$pluginXmlLines
`t`t`t`t`t</plugins>
`t`t`t`t</group>
`t`t`t</optionalFileGroups>
`t`t</installStep>
`t</installSteps>
</config>
"@

Set-Content -LiteralPath $moduleConfigPath -Value $moduleConfigXml -Encoding UTF8
Write-Host "Updated FOMOD ModuleConfig.xml"

# Create installer zip
$installerZipPath = Join-Path $AssetDir "PackRat-Nexus-FOMOD-$Version.zip"
$archivePaths = @(
    (Join-Path $fomodRootPath "fomod"),
    (Join-Path $fomodRootPath "data")
)

foreach ($archivePath in $archivePaths) {
    if (-not (Test-Path -LiteralPath $archivePath)) {
        throw "Cannot create installer zip: path does not exist: $archivePath"
    }
}

if (Test-Path -LiteralPath $installerZipPath) {
    Remove-Item -LiteralPath $installerZipPath -Force
}

Compress-Archive -Path $archivePaths -DestinationPath $installerZipPath -CompressionLevel Optimal
Write-Host "Created FOMOD installer: $installerZipPath"
